# Generated by Django 5.1.5 on 2025-08-22 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsIngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('sender', models.CharField(blank=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField()),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parsed_merchant', models.CharField(blank=True, max_length=128, null=True)),
                ('parsed_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_txn_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'parsed_ref'], name='expenses_sm_user_id_97b232_idx')],
            },
        ),
    ]
